package com.ibm.pmc.ticket.common.validation;

public enum Error {
    FILE_ALREADY_EXIST,
    FILE_UPLOAD_IO_EXCEPTION,
    FILE_DELETE_IO_EXCEPTION,
    FIND_TICKET_FILES_EXCEPTION,
    UNKNOWN_ERROR,
    INVALID_CAPTCHA,
    INVALID_PASSWORD,
    INVALID_USERNAME,
    INVALID_USERNAME_OR_PASSWORD,
    USERNAME_OR_EMAIL_LARGE_THAN_100,
    PASSWORD_LARGE_THAN_100,
    USERNAME_OR_EMAIL_REQUIRED,
    PASSWORD_REQUIRED,
    INVALID_EMAIL_ADDRESS,
    TICKET_TITLE_REQUIRED,
    TICKET_TITLE_LARGE_THAN_255,
    TICKET_MODULE_REQUIRED,
    TICKET_CONTENT_REQUIRED,
    REPLY_CONTENT_REQUIRED,
    TICKET_INPUT_CLOSED,
    MODULES_REQUIRED,
    EMAIL_REQUIRED,
    DUPLICATE_USERNAME_OR_EMAIL,
    TICKET_INPUT_ERROR
}
